### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [johnhenry/async-itertools#7]
Hi @johnhenry. The `package.json` file refers to a MIT license [here](https://github.com/johnhenry/async-itertools/blob/73e658ae2879c47fda4acdc70d608fee78984ff2/package.json#L35) but there is no license text inside the repository. Do you mind clarifying the exact license text (if any) under which the code is released?

**Comment by johnhenry** [comment]
Apologies. I've added the license. I'm in the process of fixing some bugs and re-vamping the documentation.
